# Generated by Django 5.2.11 on 2026-02-07 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smtsgg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcount',
            name='latest_search',
            field=models.TimeField(default=datetime.datetime(2026, 2, 7, 6, 37, 45, 976272, tzinfo=datetime.timezone.utc)),
        ),
    ]
